// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package exemples.javarmi.appelsretour;

public final class Callback_Stub
    extends java.rmi.server.RemoteStub
    implements exemples.javarmi.appelsretour.ICallback, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_doCallback_0;
    
    static {
	try {
	    $method_doCallback_0 = exemples.javarmi.appelsretour.ICallback.class.getMethod("doCallback", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Callback_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of doCallback(String)
    public void doCallback(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_doCallback_0, new java.lang.Object[] {$param_String_1}, -6739753569364918073L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
