// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package exemples.javarmi.annuairefactory;

public final class Annuaire_Stub
    extends java.rmi.server.RemoteStub
    implements exemples.javarmi.annuairefactory.AnnuaireInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_inserer_0;
    private static java.lang.reflect.Method $method_rechercher_1;
    private static java.lang.reflect.Method $method_supprimer_2;
    
    static {
	try {
	    $method_inserer_0 = exemples.javarmi.annuairefactory.AnnuaireInterface.class.getMethod("inserer", new java.lang.Class[] {java.lang.String.class, exemples.javarmi.annuairefactory.Information.class});
	    $method_rechercher_1 = exemples.javarmi.annuairefactory.AnnuaireInterface.class.getMethod("rechercher", new java.lang.Class[] {java.lang.String.class});
	    $method_supprimer_2 = exemples.javarmi.annuairefactory.AnnuaireInterface.class.getMethod("supprimer", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Annuaire_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of inserer(String, Information)
    public boolean inserer(java.lang.String $param_String_1, exemples.javarmi.annuairefactory.Information $param_Information_2)
	throws exemples.javarmi.annuairefactory.ExisteDeja, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_inserer_0, new java.lang.Object[] {$param_String_1, $param_Information_2}, 5248484370582633960L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (exemples.javarmi.annuairefactory.ExisteDeja e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of rechercher(String)
    public exemples.javarmi.annuairefactory.Information rechercher(java.lang.String $param_String_1)
	throws exemples.javarmi.annuairefactory.PasTrouve, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_rechercher_1, new java.lang.Object[] {$param_String_1}, 3862661397211324086L);
	    return ((exemples.javarmi.annuairefactory.Information) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (exemples.javarmi.annuairefactory.PasTrouve e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of supprimer(String)
    public boolean supprimer(java.lang.String $param_String_1)
	throws exemples.javarmi.annuairefactory.PasTrouve, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_supprimer_2, new java.lang.Object[] {$param_String_1}, -185942145801879182L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (exemples.javarmi.annuairefactory.PasTrouve e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
